ref:
  as: telcov10n-metal-single-node-spoke-kpis-hacks-deploy
  commands: telcov10n-metal-single-node-spoke-kpis-hacks-deploy-commands.sh
  from: src
  resources:
    requests:
      cpu: 1000m
      memory: 500Mi
  credentials:
  - namespace: test-credentials
    name: telcov10n-ansible-group-all
    mount_path: /var/run/telcov10n/ansible-group-all
  - namespace: test-credentials
    name: helix92-telcoqe-eng-rdu2-dc-redhat-com
    mount_path: /var/run/telcov10n/helix92-telcoqe-eng-rdu2-dc-redhat-com
  - namespace: test-credentials
    name: helix72-telcoqe-eng-rdu2-dc-redhat-com
    mount_path: /var/run/telcov10n/helix72-telcoqe-eng-rdu2-dc-redhat-com
  - namespace: test-credentials
    name: telcov10n-ztp-left-shifting
    mount_path: /var/run/telcov10n/ztp-left-shifting
  env:
  - name: AUX_HOST
    default: ""
    documentation: ""
  - name: OCP_SPOKE_VERSION
    default: ""
    documentation: |-
      Like 4.18, 4.19...
  - name: GITEA_NAMESPACE
    default: "ztp-gitea"
    documentation: |-
      Gitea k8s namespace where all its k8s related objects will be created
  - name: LOCK_TIMEOUT
    default: "18000"
    documentation: |-
      How long the lock can be hold at most. (default 5 hours; 5 * 60 * 60 = 1800)
  documentation: |-
    This step allows to adapt the SNO Spoke cluster deployment for
    the new baremetal server pool in the new lab location
